# Generated by Django 3.2.5 on 2021-07-05 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('email', models.CharField(max_length=128)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('done', 'Done')], default='draft', max_length=16)),
                ('date', models.DateField()),
                ('active', models.BooleanField(default=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='logins.profile')),
            ],
        ),
        migrations.CreateModel(
            name='LoginRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(max_length=512)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='logins.profile')),
            ],
        ),
    ]
